### ISSUE TITLE
LUA error

### ISSUE THREAD

**Issue by Andf** [Cilraaz/EmoteLDB#1]
Receving the following LUA error after logging in.

`28x EmoteLDB\LibQTip-ELDB.lua:542: attempt to call method 'GetBackdrop' (a nil value)
[string "@EmoteLDB\LibQTip-ELDB.lua"]:542: in function <EmoteLDB\LibQTip-ELDB.lua:538>
[string "@EmoteLDB\LibQTip-ELDB.lua"]:133: in function `Acquire'
[string "@EmoteLDB\EmoteLDB-v2020.11.20.6.lua"]:333: in function `OnEnter'
[string "@Bazooka\Bazooka-v2.9.9.lua"]:1583: in function `showTip'
[string "@Bazooka\Bazooka-v2.9.9.lua"]:1388: in function <Bazooka\Bazooka.lua:1379>

Locals:
tooltip = <unnamed> {
 0 = <userdata>
 OnBackdropLoaded = <function> defined @SharedXML\Backdrop.lua:144
 GetBackdropColor = <function> defined @SharedXML\Backdrop.lua:382
 SetupTextureCoordinates = <function> defined @SharedXML\Backdrop.lua:206
 OnBackdropSizeChanged = <function> defined @SharedXML\Backdrop.lua:174
 HasBackdropInfo = <function> defined @SharedXML\Backdrop.lua:270
 SetBackdropBorderColor = <function> defined @SharedXML\Backdrop.lua:414
 scrollFrame = <unnamed> {
 }
 GetEdgeSize = <function> defined @SharedXML\Backdrop.lua:180
 scrollChild = <unnamed> {
 }
 ApplyBackdrop = <function> defined @SharedXML\Backdrop.lua:286
 SetBackdrop = <function> defined @SharedXML\Backdrop.lua:321
 ClearBackdrop = <function> defined @SharedXML\Backdrop.lua:274
 GetBackdropBorderColor = <function> defined @SharedXML\Backdrop.lua:401
 GetBackdrop = <function> defined @SharedXML\Backdrop.lua:339
 SetupPieceVisuals = <function> defined @SharedXML\Backdrop.lua:238
 SetBackdropColor = <function> defined @SharedXML\Backdrop.lua:391
 SetBorderBlendMode = <function> defined @SharedXML\Backdrop.lua:258
}
key = "EmoteLDBTooltip"
(*temporary) = nil
(*temporary) = GameTooltip {
 0 = <userdata>
 textLeft1Font = "GameTooltipHeaderText"
 ItemTooltip = <unnamed> {
 }
 SetHyperlink = <function> defined =[C]:-1
 SetGuildBankItem = <function> defined =[C]:-1
 updateTooltipTimer = 0.109000
 SetVoidDepositItem = <function> defined =[C]:-1
 SetVoidWithdrawalItem = <function> defined =[C]:-1
 hasMoney = 1
 SetTradeTargetItem = <function> defined =[C]:-1
 SetItemKey = <function> defined =[C]:-1
 TextRight1 = GameTooltipTextRight1 {
 }
 comparing = false
 ClearLines = <function> defined =[C]:-1
 SetSocketGem = <function> defined =[C]:-1
 SetItemByID = <function> defined =[C]:-1
 Show = <function> defined =[C]:-1
 Hide = <function> defined =[C]:-1
 textRight2Font = "GameTooltipText"
 SetHeirloomByItemID = <function> defined =[C]:-1
 SetLootItem = <function> defined =[C]:-1
 SetQuestItem = <function> defined =[C]:-1
 SetExistingSocketGem = <function> defined =[C]:-1
 waitingForData = false
 SetTrainerService = <function> defined =[C]:-1
 numMoneyFrames = 1
 SetCurrencyToken = <function> defined @Altoholic\Services\Tooltip.lua:562
 SetRecipeResultItem = <function> defined =[C]:-1
 SetRecipeReagentItem = <function> defined @Altoholic\Services\Tooltip.lua:562
 SetBuybackItem = <function> defined =[C]:-1
 shoppingTooltips = <table> {
 }
 SetWeeklyReward = <function> defined =[C]:-1
 SetMerchantItem = <function> defined =[C]:-1
 SetQuestLogItem = <function> defined =[C]:-1
 SetInboxItem = <function> defined =[C]:-1
 BottomOverlay = <unnamed> {
 }
 layoutType = "TooltipDefaultLayout"
 SetTradePlayerItem = <function> defined =[C]:-1
 textRight1Font = "GameTooltipHeaderText"
 SetSendMailItem = <function> defined =[C]:-1
 SetMerchantCostItem = <function> defined @TradeSkillMaster\LibTSM\Service\ItemTooltipClasses\Wrapper.lua:105
 NineSlice = <unnamed> {
 }
 textLeft2Font = "GameTooltipText"
 SetLootRollItem = <function> defined =[C]:-1
 TextRight2 = GameTooltipTextRight2 {
 }
 TextLeft2 = GameTooltipTextLeft2 {
 }
 SetInventoryItem = <function> defined =[C]:-1
 SetAuctionSellItem = <function> defined @TradeSkillMaster\LibTSM\Service\ItemTooltipClasses\Wrapper.lua:105
 SetBagItem = <function> defined =[C]:-1
 needsReset = true
 TextLeft1 = GameTooltipTextLeft1 {
 }
 SetVoidItem = <function> defined =[C]:-1
 TopOverlay = <unnamed> {
 }
 SetAuctionItem = <function> defined @TradeSkillMaster\LibTSM\Service\ItemTooltipClasses\Wrapper.lua:105
}
(*temporary) = "attempt to call method 'GetBackdrop' (a nil value)"
GameTooltip = GameTooltip {
 0 = <userdata>
 textLeft1Font = "GameTooltipHeaderText"
 ItemTooltip = <unnamed> {
 }
 SetHyperlink = <function> defined =[C]:-1
 SetGuildBankItem = <function> defined =[C]:-1
 updateTooltipTimer =`

**Comment by Andf** [comment]
Not sure if it's EmoteLDB ort Bazooka...

**Comment by Cilraaz** [comment]
It's technically being generated from Bazooka, but from the version of LibQTip inside EmoteLDB. Unfortunately, it looks like you're running a very old version of EmoteLDB (Nov 20, 2020). My version of LibQTip was patched on Nov 4, 2021 to mix-in BackdropTemplateMixin to avoid this specific error. Please try updating to the latest version (9.2.0.01 was released Feb 27, 2022) to see if it fixes your issue.

**Comment by Andf** [comment]
Uhm... that's weird, I downloaded EmoteLDB from Curse a couple of weeks ago. I'll check versions later today and I'll let you know. 

Many thanks for your swift response!

**Comment by Andf** [comment]
I think I know what happened; version on Curseforge seems to be marked as Beta, so Ajour downgraded it using latest stable. 
Everything is working fine using latest version, many thanks!
