### ISSUE TITLE
on call menu?

### ISSUE THREAD

**Issue by Darkvulpine** [Cilraaz/EmoteLDB#2]
I cannot find a way to bring this up on call.  So far I can only use it via the minimap, and sometimes it will close before I can mouse down to click on any of the options.

Is there a way to have this be more of an on-call  function either /slash command for a macro?

Ideally I would like this to be functional with Consoleport in some way, to make emoting with gamepad a little easier, without having to setup multiple macros.

**Comment by Cilraaz** [comment]
Never replied to this issue after resolving the issue.

The hover menu has long since had a delay added to its closing time.

There are currently no plans to open the menu with a slash command or to add ConsolePort compatibility/functionality.
